theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
title: Dan Pilch’s blog
description: Personal and professional blog
author: Dan Pilch
#collections:
#  posts:
#    output: true
#    permalink: /blog/:year/:month/:day/:title:output_ext
