theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
title: Dan Pilch’s blog
description: Personal and professional blog
author: Dan Pilch
collections:
  posts:
    output: true
    #permalink: /posts/blog/:short_year/:month/:day/:title:output_ext
    permalink: /:year/:month/:day/:title:output_ext
